# Generated by Django 4.1.7 on 2023-03-22 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_id_alter_todolist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 12, 20, 7, 252067, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
