# Generated by Django 4.1.7 on 2023-03-22 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_todolist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 15, 4, 35, 51242, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
